# Generated by Django 3.0.8 on 2020-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='fileURL',
            field=models.CharField(default='', max_length=100, verbose_name='Fil URL'),
        ),
    ]
