# Generated by Django 3.0.8 on 2020-08-07 01:27

import MemeApp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_auto_20200727_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='meme',
            name='file',
        ),
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.FileField(default='', storage=MemeApp.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='meme',
            name='video',
            field=models.FileField(default='', storage=MemeApp.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
