# Generated by Django 3.0.8 on 2020-08-12 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0003_auto_20200812_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='memefy'),
        ),
    ]
